name: lesson_search
description: "查课 App"
publish_to: 'none'
version: 0.3.5+12

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 路由
  go_router: ^14.8.1

  # 网络
  dio: ^5.7.0

  # 本地数据库
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28

  # 序列化
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.3
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # 代码生成
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
